var g,aa=aa||{},n=this;function p(a){return void 0!==a}function ba(){}
function ca(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function q(a){return"array"==ca(a)}function da(a){var b=ca(a);return"array"==b||"object"==b&&"number"==typeof a.length}function u(a){return"string"==typeof a}function v(a){return"number"==typeof a}function x(a){return"function"==ca(a)}function ea(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function fa(a){return a[ga]||(a[ga]=++ha)}var ga="closure_uid_"+(1E9*Math.random()>>>0),ha=0;
function ia(a,b,c){return a.call.apply(a.bind,arguments)}function ja(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function y(a,b,c){y=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ia:ja;return y.apply(null,arguments)}var ka=Date.now||function(){return+new Date};
function A(a,b){function c(){}c.prototype=b.prototype;a.k=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Rd=function(a,c,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[c].apply(a,h)}};function B(a){if(Error.captureStackTrace)Error.captureStackTrace(this,B);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}A(B,Error);B.prototype.name="CustomError";var la;var ma=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};function na(a){if(!oa.test(a))return a;-1!=a.indexOf("\x26")&&(a=a.replace(pa,"\x26amp;"));-1!=a.indexOf("\x3c")&&(a=a.replace(qa,"\x26lt;"));-1!=a.indexOf("\x3e")&&(a=a.replace(ra,"\x26gt;"));-1!=a.indexOf('"')&&(a=a.replace(sa,"\x26quot;"));-1!=a.indexOf("'")&&(a=a.replace(ta,"\x26#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(ua,"\x26#0;"));return a}
var pa=/&/g,qa=/</g,ra=/>/g,sa=/"/g,ta=/'/g,ua=/\x00/g,oa=/[\x00&<>"']/;function C(a,b){return-1!=a.indexOf(b)}function va(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")}function wa(a,b){return a<b?-1:a>b?1:0}function xa(){return"transform".replace(/\-([a-z])/g,function(a,b){return b.toUpperCase()})}
function ya(a){var b=u(void 0)?va(void 0):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};var D=Array.prototype,za=D.indexOf?function(a,b,c){return D.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(u(a))return u(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},E=D.forEach?function(a,b,c){D.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=u(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Aa=D.filter?function(a,b,c){return D.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=u(a)?
a.split(""):a,k=0;k<d;k++)if(k in h){var l=h[k];b.call(c,l,k,a)&&(e[f++]=l)}return e},Ba=D.map?function(a,b,c){return D.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=u(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e},Ca=D.some?function(a,b,c){return D.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=u(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1},Da=D.every?function(a,b,c){return D.every.call(a,b,c)}:function(a,b,c){for(var d=
a.length,e=u(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};function Ea(a){var b=Fa(a,Ga,void 0);return 0>b?null:u(a)?a.charAt(b):a[b]}function Fa(a,b,c){for(var d=a.length,e=u(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1}function Ha(a){return D.concat.apply(D,arguments)}function Ia(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}
function Ja(a,b,c){return 2>=arguments.length?D.slice.call(a,b):D.slice.call(a,b,c)};var G;a:{var Ka=n.navigator;if(Ka){var La=Ka.userAgent;if(La){G=La;break a}}G=""};function Ma(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function Na(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b}function Oa(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b}function Pa(){var a=Qa,b;for(b in a)return!1;return!0}var Ra="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
function Sa(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ra.length;f++)c=Ra[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}}function Ta(a){var b=arguments.length;if(1==b&&q(arguments[0]))return Ta.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};var Ua=C(G,"Opera")||C(G,"OPR"),H=C(G,"Trident")||C(G,"MSIE"),J=C(G,"Gecko")&&!C(G.toLowerCase(),"webkit")&&!(C(G,"Trident")||C(G,"MSIE")),K=C(G.toLowerCase(),"webkit"),Va=C(G,"Macintosh"),Wa,Xa=n.navigator||null;Wa=!!Xa&&C(Xa.appVersion||"","X11");function Ya(){var a=n.document;return a?a.documentMode:void 0}
var Za=function(){var a="",b;if(Ua&&n.opera)return a=n.opera.version,x(a)?a():a;J?b=/rv\:([^\);]+)(\)|;)/:H?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:K&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(G))?a[1]:"");return H&&(b=Ya(),b>parseFloat(a))?String(b):a}(),$a={};
function L(a){var b;if(!(b=$a[a])){b=0;for(var c=ma(String(Za)).split("."),d=ma(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",k=d[f]||"",l=RegExp("(\\d*)(\\D*)","g"),r=RegExp("(\\d*)(\\D*)","g");do{var t=l.exec(h)||["","",""],z=r.exec(k)||["","",""];if(0==t[0].length&&0==z[0].length)break;b=wa(0==t[1].length?0:parseInt(t[1],10),0==z[1].length?0:parseInt(z[1],10))||wa(0==t[2].length,0==z[2].length)||wa(t[2],z[2])}while(0==b)}b=$a[a]=0<=b}return b}
var ab=n.document,bb=ab&&H?Ya()||("CSS1Compat"==ab.compatMode?parseInt(Za,10):5):void 0;var cb=!H||H&&9<=bb;!J&&!H||H&&H&&9<=bb||J&&L("1.9.1");H&&L("9");Ta("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));Ta("action","cite","data","formaction","href","manifest","poster","src");Ta("embed","iframe","link","object","script","style","template");function M(a,b){this.x=p(a)?a:0;this.y=p(b)?b:0}g=M.prototype;g.clone=function(){return new M(this.x,this.y)};function db(a,b){return new M(a.x-b.x,a.y-b.y)}g.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};g.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};g.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
g.translate=function(a,b){a instanceof M?(this.x+=a.x,this.y+=a.y):(this.x+=a,v(b)&&(this.y+=b));return this};g.scale=function(a,b){var c=v(b)?b:a;this.x*=a;this.y*=c;return this};function eb(a,b){this.width=a;this.height=b}g=eb.prototype;g.clone=function(){return new eb(this.width,this.height)};g.isEmpty=function(){return!(this.width*this.height)};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.scale=function(a,b){var c=v(b)?b:a;this.width*=a;this.height*=c;return this};function fb(a){return a?new gb(N(a)):la||(la=new gb)}function hb(a){var b=document;return u(a)?b.getElementById(a):a}function ib(){var a=document;return a.querySelectorAll&&a.querySelector?a.querySelectorAll(".autocomplete-nominatim"):jb()}
function jb(){var a,b,c,d;a=document;if(a.querySelectorAll&&a.querySelector)return a.querySelectorAll(".autocomplete-nominatim");if(a.getElementsByClassName){var e=a.getElementsByClassName("autocomplete-nominatim");return e}e=a.getElementsByTagName("*");d={};for(b=c=0;a=e[b];b++){var f=a.className,h;if(h="function"==typeof f.split)h=0<=za(f.split(/\s+/),"autocomplete-nominatim");h&&(d[c++]=a)}d.length=c;return d}
function kb(a,b){Ma(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in lb?a.setAttribute(lb[d],b):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})}var lb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function mb(a){return K||"CSS1Compat"!=a.compatMode?a.body||a.documentElement:a.documentElement}function nb(a){return a.parentWindow||a.defaultView}function O(a,b,c){return ob(document,arguments)}
function ob(a,b){var c=b[0],d=b[1];if(!cb&&d&&(d.name||d.type)){c=["\x3c",c];d.name&&c.push(' name\x3d"',na(d.name),'"');if(d.type){c.push(' type\x3d"',na(d.type),'"');var e={};Sa(e,d);delete e.type;d=e}c.push("\x3e");c=c.join("")}c=a.createElement(c);d&&(u(d)?c.className=d:q(d)?c.className=d.join(" "):kb(c,d));2<b.length&&pb(a,c,b,2);return c}
function pb(a,b,c,d){function e(c){c&&b.appendChild(u(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];!da(f)||ea(f)&&0<f.nodeType?e(f):E(qb(f)?Ia(f):f,e)}}function rb(a,b){a.appendChild(b)}function sb(a,b){pb(N(a),a,arguments,1)}function tb(a){for(var b;b=a.firstChild;)a.removeChild(b)}function ub(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)}function vb(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function N(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function qb(a){if(a&&"number"==typeof a.length){if(ea(a))return"function"==typeof a.item||"string"==typeof a.item;if(x(a))return"function"==typeof a.item}return!1}function gb(a){this.s=a||n.document||document}g=gb.prototype;g.Xb=function(a,b,c){return ob(this.s,arguments)};g.createElement=function(a){return this.s.createElement(a)};g.createTextNode=function(a){return this.s.createTextNode(String(a))};function wb(a){return"CSS1Compat"==a.s.compatMode}
function xb(a){var b=a.s;a=mb(b);b=nb(b);return H&&L("10")&&b.pageYOffset!=a.scrollTop?new M(a.scrollLeft,a.scrollTop):new M(b.pageXOffset||a.scrollLeft,b.pageYOffset||a.scrollTop)}g.appendChild=rb;g.append=sb;g.canHaveChildren=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.Ad=tb;g.removeNode=vb;g.contains=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};function yb(a,b){this.f=a||[];this.Ob=!b}yb.prototype.cb=function(a,b,c){if(this.Ob){var d=this.f,e=zb(a,b,d);0==e.length&&(e=Ab(a,b,d));b=e}else b=zb(a,b,this.f);c(a,b)};function zb(a,b,c){var d=[];if(""!=a){a=va(a);a=new RegExp("(^|\\W+)"+a,"i");for(var e=0;e<c.length&&d.length<b;e++){var f=c[e];String(f).match(a)&&d.push(f)}}return d}
function Ab(a,b,c){for(var d=[],e=0;e<c.length;e++){var f=c[e],h=a.toLowerCase(),k=String(f).toLowerCase(),l=0;if(-1!=k.indexOf(h))l=parseInt((k.indexOf(h)/4).toString(),10);else for(var r=h.split(""),t=-1,z=10,F=0,Y;Y=r[F];F++)Y=k.indexOf(Y),Y>t?(t=Y-t-1,t>z-5&&(t=z-5),l+=t,t=Y):(l+=z,z+=5);l<6*h.length&&d.push({Jd:f,Jc:l,index:e})}d.sort(function(a,b){var c=a.Jc-b.Jc;return 0!=c?c:a.index-b.index});a=[];for(F=0;F<b&&F<d.length;F++)a.push(d[F].Jd);return a};var Bb=!H||H&&9<=bb,Cb=H&&!L("9");!K||L("528");J&&L("1.9b")||H&&L("8")||Ua&&L("9.5")||K&&L("528");J&&!L("8")||H&&L("9");function P(){0!=Db&&(Eb[fa(this)]=this);this.Aa=this.Aa;this.$a=this.$a}var Db=0,Eb={};P.prototype.Aa=!1;P.prototype.S=function(){if(!this.Aa&&(this.Aa=!0,this.e(),0!=Db)){var a=fa(this);delete Eb[a]}};P.prototype.e=function(){if(this.$a)for(;this.$a.length;)this.$a.shift()()};function Fb(a){a&&"function"==typeof a.S&&a.S()};function Q(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.ja=!1;this.Hc=!0}Q.prototype.e=function(){};Q.prototype.S=function(){};Q.prototype.stopPropagation=function(){this.ja=!0};Q.prototype.preventDefault=function(){this.defaultPrevented=!0;this.Hc=!1};function Gb(a){Gb[" "](a);return a}Gb[" "]=ba;function Hb(a,b){Q.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.C=this.state=null;if(a){this.C=a;var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(J){var e;a:{try{Gb(d.nodeName);e=!0;break a}catch(f){}e=!1}e||(d=null)}}else"mouseover"==
c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;Object.defineProperties?Object.defineProperties(this,{offsetX:{configurable:!0,enumerable:!0,get:this.cc,set:this.Hd},offsetY:{configurable:!0,enumerable:!0,get:this.dc,set:this.Id}}):(this.offsetX=this.cc(),this.offsetY=this.dc());this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;
this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.state=a.state;a.defaultPrevented&&this.preventDefault()}}A(Hb,Q);g=Hb.prototype;g.stopPropagation=function(){Hb.k.stopPropagation.call(this);this.C.stopPropagation?this.C.stopPropagation():this.C.cancelBubble=!0};
g.preventDefault=function(){Hb.k.preventDefault.call(this);var a=this.C;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Cb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};g.e=function(){};g.cc=function(){return K||void 0!==this.C.offsetX?this.C.offsetX:this.C.layerX};g.Hd=function(a){Object.defineProperties(this,{offsetX:{writable:!0,enumerable:!0,configurable:!0,value:a}})};g.dc=function(){return K||void 0!==this.C.offsetY?this.C.offsetY:this.C.layerY};
g.Id=function(a){Object.defineProperties(this,{offsetY:{writable:!0,enumerable:!0,configurable:!0,value:a}})};var Ib="closure_listenable_"+(1E6*Math.random()|0);function Jb(a){return!(!a||!a[Ib])}var Kb=0;function Lb(a,b,c,d,e){this.ia=a;this.bb=null;this.src=b;this.type=c;this.Oa=!!d;this.Q=e;this.key=++Kb;this.ua=this.Na=!1}function Mb(a){a.ua=!0;a.ia=null;a.bb=null;a.src=null;a.Q=null};function Nb(a){this.src=a;this.o={};this.Ka=0}Nb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.o[f];a||(a=this.o[f]=[],this.Ka++);var h=Ob(a,b,d,e);-1<h?(b=a[h],c||(b.Na=!1)):(b=new Lb(b,this.src,f,!!d,e),b.Na=c,a.push(b));return b};Nb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.o))return!1;var e=this.o[a];b=Ob(e,b,c,d);return-1<b?(Mb(e[b]),D.splice.call(e,b,1),0==e.length&&(delete this.o[a],this.Ka--),!0):!1};
function Pb(a,b){var c=b.type;if(!(c in a.o))return!1;var d=a.o[c],e=za(d,b),f;(f=0<=e)&&D.splice.call(d,e,1);f&&(Mb(b),0==a.o[c].length&&(delete a.o[c],a.Ka--));return f}Nb.prototype.Fa=function(a){a=a&&a.toString();var b=0,c;for(c in this.o)if(!a||c==a){for(var d=this.o[c],e=0;e<d.length;e++)++b,Mb(d[e]);delete this.o[c];this.Ka--}return b};Nb.prototype.Ba=function(a,b,c,d){a=this.o[a.toString()];var e=-1;a&&(e=Ob(a,b,c,d));return-1<e?a[e]:null};
function Ob(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.ua&&f.ia==b&&f.Oa==!!c&&f.Q==d)return e}return-1};var Qb="closure_lm_"+(1E6*Math.random()|0),Rb={},Sb=0;function S(a,b,c,d,e){if(q(b)){for(var f=0;f<b.length;f++)S(a,b[f],c,d,e);return null}c=Tb(c);return Jb(a)?a.F(b,c,d,e):Ub(a,b,c,!1,d,e)}function Ub(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=!!e,k=Vb(a);k||(a[Qb]=k=new Nb(a));c=k.add(b,c,d,e,f);if(c.bb)return c;d=Wb();c.bb=d;d.src=a;d.ia=c;a.addEventListener?a.addEventListener(b.toString(),d,h):a.attachEvent(Xb(b.toString()),d);Sb++;return c}
function Wb(){var a=Yb,b=Bb?function(c){return a.call(b.src,b.ia,c)}:function(c){c=a.call(b.src,b.ia,c);if(!c)return c};return b}function Zb(a,b,c,d,e){if(q(b)){for(var f=0;f<b.length;f++)Zb(a,b[f],c,d,e);return null}c=Tb(c);return Jb(a)?a.oc(b,c,d,e):Ub(a,b,c,!0,d,e)}function $b(a,b,c,d,e){if(q(b))for(var f=0;f<b.length;f++)$b(a,b[f],c,d,e);else c=Tb(c),Jb(a)?a.A(b,c,d,e):a&&(a=Vb(a))&&(b=a.Ba(b,c,!!d,e))&&ac(b)}
function ac(a){if(v(a)||!a||a.ua)return!1;var b=a.src;if(Jb(b))return Pb(b.J,a);var c=a.type,d=a.bb;b.removeEventListener?b.removeEventListener(c,d,a.Oa):b.detachEvent&&b.detachEvent(Xb(c),d);Sb--;(c=Vb(b))?(Pb(c,a),0==c.Ka&&(c.src=null,b[Qb]=null)):Mb(a);return!0}function bc(a){if(a)if(Jb(a))a.J&&a.J.Fa(void 0);else if(a=Vb(a)){var b=0,c;for(c in a.o)for(var d=a.o[c].concat(),e=0;e<d.length;++e)ac(d[e])&&++b}}function Xb(a){return a in Rb?Rb[a]:Rb[a]="on"+a}
function cc(a,b,c,d){var e=!0;if(a=Vb(a))if(b=a.o[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Oa==c&&!f.ua&&(f=dc(f,d),e=e&&!1!==f)}return e}function dc(a,b){var c=a.ia,d=a.Q||a.src;a.Na&&ac(a);return c.call(d,b)}
function Yb(a,b){if(a.ua)return!0;if(!Bb){var c;if(!(c=b))a:{c=["window","event"];for(var d=n,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break a}c=d}e=c;c=new Hb(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){a:{var f=!1;if(0==e.keyCode)try{e.keyCode=-1;break a}catch(h){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.currentTarget;f;f=f.parentNode)e.push(f);for(var f=a.type,k=e.length-1;!c.ja&&0<=k;k--){c.currentTarget=e[k];var l=cc(e[k],f,!0,c),d=d&&l}for(k=0;!c.ja&&k<
e.length;k++)c.currentTarget=e[k],l=cc(e[k],f,!1,c),d=d&&l}return d}return dc(a,new Hb(b,this))}function Vb(a){a=a[Qb];return a instanceof Nb?a:null}var ec="__closure_events_fn_"+(1E9*Math.random()>>>0);function Tb(a){if(x(a))return a;a[ec]||(a[ec]=function(b){return a.handleEvent(b)});return a[ec]};function T(){P.call(this);this.J=new Nb(this);this.Wc=this;this.Ib=null}A(T,P);T.prototype[Ib]=!0;g=T.prototype;g.addEventListener=function(a,b,c,d){S(this,a,b,c,d)};g.removeEventListener=function(a,b,c,d){$b(this,a,b,c,d)};
g.dispatchEvent=function(a){var b,c=this.Ib;if(c)for(b=[];c;c=c.Ib)b.push(c);var c=this.Wc,d=a.type||a;if(u(a))a=new Q(a,c);else if(a instanceof Q)a.target=a.target||c;else{var e=a;a=new Q(d,c);Sa(a,e)}var e=!0,f;if(b)for(var h=b.length-1;!a.ja&&0<=h;h--)f=a.currentTarget=b[h],e=fc(f,d,!0,a)&&e;a.ja||(f=a.currentTarget=c,e=fc(f,d,!0,a)&&e,a.ja||(e=fc(f,d,!1,a)&&e));if(b)for(h=0;!a.ja&&h<b.length;h++)f=a.currentTarget=b[h],e=fc(f,d,!1,a)&&e;return e};
g.e=function(){T.k.e.call(this);this.J&&this.J.Fa(void 0);this.Ib=null};g.F=function(a,b,c,d){return this.J.add(String(a),b,!1,c,d)};g.oc=function(a,b,c,d){return this.J.add(String(a),b,!0,c,d)};g.A=function(a,b,c,d){return this.J.remove(String(a),b,c,d)};function fc(a,b,c,d){b=a.J.o[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var h=b[f];if(h&&!h.ua&&h.Oa==c){var k=h.ia,l=h.Q||h.src;h.Na&&Pb(a.J,h);e=!1!==k.call(l,d)&&e}}return e&&0!=d.Hc}
g.Ba=function(a,b,c,d){return this.J.Ba(String(a),b,c,d)};function gc(a,b,c){T.call(this);this.aa=a;this.Ha=c;this.H=b;S(b,[hc,ic,jc,kc],this.handleEvent,!1,this);this.L=null;this.f=[];this.Z=-1;this.p=0;this.ea=this.n=null;this.jc={}}A(gc,T);g=gc.prototype;g.vd=10;g.Yc=!0;g.Tb=!1;g.Vc=!1;g.Nc=!1;var hc="hilite",ic="select",kc="dismiss",jc="canceldismiss";g=gc.prototype;
g.handleEvent=function(a){var b=this.aa;if(a.target==this.H)switch(a.type){case hc:this.U(a.row);break;case ic:var c=!1;if(v(a.row)){a=a.row;var d=this.f[lc(this,a)],c=!!d&&b.Ab&&b.Ab(d);d&&!c&&this.Z!=a&&this.U(a)}c||mc(this);break;case jc:nc(this);break;case kc:oc(this)}};function pc(a){for(var b=a.p+a.f.length-1,c=a.Z,d=0;d<a.f.length;d++){if(c>=a.p&&c<b)c++;else if(-1==c)c=a.p;else if(a.Tb&&c==b){a.U(-1);break}else if(a.Vc&&c==b)c=a.p;else break;if(a.U(c))break}}
function qc(a){for(var b=a.p+a.f.length-1,c=a.Z,d=0;d<a.f.length;d++){if(c>a.p)c--;else if(a.Tb&&c==a.p){a.U(-1);break}else if(!a.Vc||-1!=c&&c!=a.p)break;else c=b;if(a.U(c))break}}g.U=function(a){var b=lc(this,a),c=this.f[b];return c&&this.aa.Ab&&this.aa.Ab(c)?!1:(this.Z=a,this.H.U(a),-1!=b)};
function mc(a){var b=lc(a,a.Z);if(-1!=b){var c=a.f[b],d=a.Ha;if(d.c){var e=c.toString();if(p(void 0)?0:d.sa){var f=rc(d,d.c.value,sc(d.c)[0]),h=tc(d,d.c.value);d.Ed.test(e)||(e=e.replace(/[\s\xa0]+$/,"")+d.dd);d.Od&&(0==f||/^[\s\xa0]*$/.test(h[f-1])||(e=" "+e),f==h.length-1&&(e+=" "));if(e!=h[f]){h[f]=e;e=d.c;(J||H&&L("9"))&&e.blur();e.value=h.join("");for(var k=0,l=0;l<=f;l++)k+=h[l].length;e.focus();f=k;h=d.c;e=f;uc(h)?h.selectionStart=e:H&&(k=vc(h),l=k[0],l.inRange(k[1])&&(e=wc(h,e),l.collapse(!0),
l.move("character",e),l.select()));h=d.c;uc(h)?h.selectionEnd=f:H&&(k=vc(h),e=k[1],k[0].inRange(e)&&(f=wc(h,f),h=wc(h,sc(h)[0]),e.collapse(!0),e.moveEnd("character",f-h),e.select()))}}else d.c.value=e;d.Kb=!0}a.Nc?(a.L=null,oc(a)):a.I();a.dispatchEvent({type:"update",row:c,index:b});a.Nc&&a.Ha.update(!0);return!0}a.I();a.dispatchEvent({type:"update",row:null,index:null});return!1}
g.I=function(){this.Z=-1;this.L=null;this.p+=this.f.length;this.f=[];window.clearTimeout(this.ea);this.ea=null;this.H.I();this.dispatchEvent("suggestionsupdate");this.dispatchEvent(kc)};function oc(a){a.ea||(a.ea=window.setTimeout(y(a.I,a),100))}g.ic=function(){return this.ea?(window.clearTimeout(this.ea),this.ea=null,!0):!1};function nc(a){a.ic()||window.setTimeout(y(a.ic,a),10)}g.e=function(){gc.k.e.call(this);delete this.jc;this.H.S();this.Ha.S();this.aa=null};
g.sd=function(a,b,c){this.L==a&&this.Ga(b,c)};g.Ga=function(a,b){var c="object"==ca(b)&&b,d=(c?c.Sd():b)?lc(this,this.Z):-1;this.p+=this.f.length;this.f=a;for(var e=[],f=0;f<a.length;++f)e.push({id:this.p+f,data:a[f]});f=null;this.n&&(f=this.jc[fa(this.n)]||this.n);this.H.Xc=f;this.H.Ga(e,this.L,this.n);f=this.Yc;c&&void 0!==c.ld()&&(f=c.ld());this.Z=-1;(f||0<=d)&&0!=e.length&&this.L&&(0<=d?this.U(this.p+d):pc(this));this.dispatchEvent("suggestionsupdate")};
function lc(a,b){var c=b-a.p;return 0>c||c>=a.f.length?-1:c}g.pb=function(a){var b=this.Ha;b.pb.apply(b,arguments)};g.update=function(a){this.Ha.update(a)};function xc(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0}function yc(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};function zc(a){n.setTimeout(function(){throw a;},0)}var Ac;
function Bc(){var a=n.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(a=function(){var a=document.createElement("iframe");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=y(function(a){if(("*"==d||a.origin==d)&&a.data==c)this.port1.onmessage()},
this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!C(G,"Trident")&&!C(G,"MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(p(c.next)){c=c.next;var a=c.Vb;c.Vb=null;a()}};return function(a){d.next={Vb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("script")?function(a){var b=document.createElement("script");b.onreadystatechange=
function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){n.setTimeout(a,0)}};function Cc(a,b){Dc||Ec();Fc||(Dc(),Fc=!0);Gc.push(new Hc(a,b))}var Dc;function Ec(){if(n.Promise&&n.Promise.resolve){var a=n.Promise.resolve();Dc=function(){a.then(Ic)}}else Dc=function(){var a=Ic;!x(n.setImmediate)||n.Window&&n.Window.prototype.setImmediate==n.setImmediate?(Ac||(Ac=Bc()),Ac(a)):n.setImmediate(a)}}var Fc=!1,Gc=[];function Ic(){for(;Gc.length;){var a=Gc;Gc=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.jd.call(c.scope)}catch(d){zc(d)}}}Fc=!1}
function Hc(a,b){this.jd=a;this.scope=b};function Jc(a,b){this.g=Kc;this.W=void 0;this.B=this.r=null;this.Qa=this.vb=!1;try{var c=this;a.call(b,function(a){Lc(c,Mc,a)},function(a){Lc(c,Nc,a)})}catch(d){Lc(this,Nc,d)}}var Kc=0,Mc=2,Nc=3;Jc.prototype.then=function(a,b,c){return Oc(this,x(a)?a:null,x(b)?b:null,c)};xc(Jc);Jc.prototype.cancel=function(a){this.g==Kc&&Cc(function(){var b=new Pc(a);Qc(this,b)},this)};
function Qc(a,b){if(a.g==Kc)if(a.r){var c=a.r;if(c.B){for(var d=0,e=-1,f=0,h;h=c.B[f];f++)if(h=h.wa)if(d++,h==a&&(e=f),0<=e&&1<d)break;0<=e&&(c.g==Kc&&1==d?Qc(c,b):(d=c.B.splice(e,1)[0],Rc(c,d,Nc,b)))}}else Lc(a,Nc,b)}function Sc(a,b){a.B&&a.B.length||a.g!=Mc&&a.g!=Nc||Tc(a);a.B||(a.B=[]);a.B.push(b)}
function Oc(a,b,c,d){var e={wa:null,sc:null,Ac:null};e.wa=new Jc(function(a,h){e.sc=b?function(c){try{var e=b.call(d,c);a(e)}catch(r){h(r)}}:a;e.Ac=c?function(b){try{var e=c.call(d,b);!p(e)&&b instanceof Pc?h(b):a(e)}catch(r){h(r)}}:h});e.wa.r=a;Sc(a,e);return e.wa}Jc.prototype.Pc=function(a){this.g=Kc;Lc(this,Mc,a)};Jc.prototype.Qc=function(a){this.g=Kc;Lc(this,Nc,a)};
function Lc(a,b,c){if(a.g==Kc){if(a==c)b=Nc,c=new TypeError("Promise cannot resolve to itself");else{if(yc(c)){a.g=1;c.then(a.Pc,a.Qc,a);return}if(ea(c))try{var d=c.then;if(x(d)){Uc(a,c,d);return}}catch(e){b=Nc,c=e}}a.W=c;a.g=b;Tc(a);b!=Nc||c instanceof Pc||Vc(a,c)}}function Uc(a,b,c){function d(b){f||(f=!0,a.Qc(b))}function e(b){f||(f=!0,a.Pc(b))}a.g=1;var f=!1;try{c.call(b,e,d)}catch(h){d(h)}}function Tc(a){a.vb||(a.vb=!0,Cc(a.hd,a))}
Jc.prototype.hd=function(){for(;this.B&&this.B.length;){var a=this.B;this.B=[];for(var b=0;b<a.length;b++)Rc(this,a[b],this.g,this.W)}this.vb=!1};function Rc(a,b,c,d){if(c==Mc)b.sc(d);else{if(b.wa)for(;a&&a.Qa;a=a.r)a.Qa=!1;b.Ac(d)}}function Vc(a,b){a.Qa=!0;Cc(function(){a.Qa&&Wc.call(null,b)})}var Wc=zc;function Pc(a){B.call(this,a)}A(Pc,B);Pc.prototype.name="cancel";function Xc(a,b){T.call(this);this.ha=a||1;this.va=b||n;this.rb=y(this.Ld,this);this.Fb=ka()}A(Xc,T);g=Xc.prototype;g.enabled=!1;g.d=null;g.setInterval=function(a){this.ha=a;this.d&&this.enabled?(this.stop(),this.start()):this.d&&this.stop()};g.Ld=function(){if(this.enabled){var a=ka()-this.Fb;0<a&&a<.8*this.ha?this.d=this.va.setTimeout(this.rb,this.ha-a):(this.d&&(this.va.clearTimeout(this.d),this.d=null),this.dispatchEvent(Yc),this.enabled&&(this.d=this.va.setTimeout(this.rb,this.ha),this.Fb=ka()))}};
g.start=function(){this.enabled=!0;this.d||(this.d=this.va.setTimeout(this.rb,this.ha),this.Fb=ka())};g.stop=function(){this.enabled=!1;this.d&&(this.va.clearTimeout(this.d),this.d=null)};g.e=function(){Xc.k.e.call(this);this.stop();delete this.va};var Yc="tick";function Zc(a,b,c){if(x(a))c&&(a=y(a,c));else if(a&&"function"==typeof a.handleEvent)a=y(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<b?-1:n.setTimeout(a,b||0)};var $c;function ad(a,b){b?a.setAttribute("role",b):a.removeAttribute("role")}function bd(a,b,c){q(c)&&(c=c.join(" "));var d="aria-"+b;""===c||void 0==c?($c||($c={atomic:!1,autocomplete:"none",dropeffect:"none",haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:"none",busy:!1,disabled:!1,hidden:!1,invalid:"false"}),c=$c,b in c?a.setAttribute(d,c[b]):a.removeAttribute(d)):a.setAttribute(d,c)}
function cd(a,b){var c="";b&&(c=b.id);bd(a,"activedescendant",c)};function sc(a){var b=0,c=0;if(uc(a))b=a.selectionStart,c=-1;else if(H){var d=vc(a),e=d[0],d=d[1];if(e.inRange(d)){e.setEndPoint("EndToStart",d);if("textarea"==a.type){d.duplicate();b=a=e.text;for(c=!1;!c;)0==e.compareEndPoints("StartToEnd",e)?c=!0:(e.moveEnd("character",-1),e.text==a?b+="\r\n":c=!0);e=[b.length,-1];return e}b=e.text.length;c=-1}}return[b,c]}
function vc(a){var b=a.ownerDocument||a.document,c=b.selection.createRange();"textarea"==a.type?(b=b.body.createTextRange(),b.moveToElementText(a)):b=a.createTextRange();return[b,c]}function wc(a,b){"textarea"==a.type&&(b=a.value.substring(0,b).replace(/(\r\n|\r|\n)/g,"\n").length);return b}function uc(a){try{return"number"==typeof a.selectionStart}catch(b){return!1}};function dd(a){P.call(this);this.qa=a;this.j={}}A(dd,P);var ed=[];g=dd.prototype;g.F=function(a,b,c,d){q(b)||(b&&(ed[0]=b.toString()),b=ed);for(var e=0;e<b.length;e++){var f=S(a,b[e],c||this.handleEvent,d||!1,this.qa||this);if(!f)break;this.j[f.key]=f}return this};g.oc=function(a,b,c,d){return fd(this,a,b,c,d)};function fd(a,b,c,d,e,f){if(q(c))for(var h=0;h<c.length;h++)fd(a,b,c[h],d,e,f);else{b=Zb(b,c,d||a.handleEvent,e,f||a.qa||a);if(!b)return a;a.j[b.key]=b}return a}
g.A=function(a,b,c,d,e){if(q(b))for(var f=0;f<b.length;f++)this.A(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.qa||this,c=Tb(c),d=!!d,b=Jb(a)?a.Ba(b,c,d,e):a?(a=Vb(a))?a.Ba(b,c,d,e):null:null,b&&(ac(b),delete this.j[b.key]);return this};g.Fa=function(){Ma(this.j,ac);this.j={}};g.e=function(){dd.k.e.call(this);this.Fa()};g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function gd(a,b,c,d,e){if(!(H||K&&L("525")))return!0;if(Va&&e)return hd(a);if(e&&!d)return!1;v(b)&&(b=id(b));if(!c&&(17==b||18==b||Va&&91==b))return!1;if(K&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}if(H&&d&&b==a)return!1;switch(a){case 13:return!0;case 27:return!K}return hd(a)}
function hd(a){if(48<=a&&57>=a||96<=a&&106>=a||65<=a&&90>=a||K&&0==a)return!0;switch(a){case 32:case 63:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:return!0;default:return!1}}function id(a){if(J)a=jd(a);else if(Va&&K)a:switch(a){case 93:a=91;break a}return a}
function jd(a){switch(a){case 61:return 187;case 59:return 186;case 173:return 189;case 224:return 91;case 0:return 224;default:return a}};function kd(a,b){T.call(this);a&&ld(this,a,b)}A(kd,T);g=kd.prototype;g.b=null;g.Va=null;g.Bb=null;g.Wa=null;g.v=-1;g.$=-1;g.nb=!1;
var md={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},nd={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},od=H||K&&L("525"),pd=Va&&J;g=kd.prototype;
g.md=function(a){K&&(17==this.v&&!a.ctrlKey||18==this.v&&!a.altKey||Va&&91==this.v&&!a.metaKey)&&(this.$=this.v=-1);-1==this.v&&(a.ctrlKey&&17!=a.keyCode?this.v=17:a.altKey&&18!=a.keyCode?this.v=18:a.metaKey&&91!=a.keyCode&&(this.v=91));od&&!gd(a.keyCode,this.v,a.shiftKey,a.ctrlKey,a.altKey)?this.handleEvent(a):(this.$=id(a.keyCode),pd&&(this.nb=a.altKey))};g.od=function(a){this.$=this.v=-1;this.nb=a.altKey};
g.handleEvent=function(a){var b=a.C,c,d,e=b.altKey;H&&"keypress"==a.type?(c=this.$,d=13!=c&&27!=c?b.keyCode:0):K&&"keypress"==a.type?(c=this.$,d=0<=b.charCode&&63232>b.charCode&&hd(c)?b.charCode:0):Ua?(c=this.$,d=hd(c)?b.keyCode:0):(c=b.keyCode||this.$,d=b.charCode||0,pd&&(e=this.nb),Va&&63==d&&224==c&&(c=191));var f=c=id(c),h=b.keyIdentifier;c?63232<=c&&c in md?f=md[c]:25==c&&a.shiftKey&&(f=9):h&&h in nd&&(f=nd[h]);a=f==this.v;this.v=f;b=new qd(f,d,a,b);b.altKey=e;this.dispatchEvent(b)};
function ld(a,b,c){a.Wa&&a.detach();a.b=b;a.Va=S(a.b,"keypress",a,c);a.Bb=S(a.b,"keydown",a.md,c,a);a.Wa=S(a.b,"keyup",a.od,c,a)}g.detach=function(){this.Va&&(ac(this.Va),ac(this.Bb),ac(this.Wa),this.Wa=this.Bb=this.Va=null);this.b=null;this.$=this.v=-1};g.e=function(){kd.k.e.call(this);this.detach()};function qd(a,b,c,d){Hb.call(this,d);this.type="key";this.keyCode=a;this.charCode=b;this.repeat=c}A(qd,Hb);var rd,sd;sd=rd=!1;var td=G;!td||-1==td.indexOf("Firefox")&&-1==td.indexOf("Camino")&&(-1!=td.indexOf("iPad")?sd=!0:-1==td.indexOf("iPhone")&&-1==td.indexOf("iPod")||(rd=!0));var ud=rd,vd=sd;function wd(a,b,c,d){P.call(this);d=d||150;this.sa=null!=c?c:!0;this.Ia=a||",;";this.dd=this.Ia.substring(0,1);a=this.sa?"[\\s"+this.Ia+"]+":"[\\s]+";this.Oc=new RegExp("^"+a+"|"+a+"$","g");this.Ed=new RegExp("\\s*["+this.Ia+"]$");this.pc=b||"";this.zd=!1;this.Cc=this.sa;this.d=0<d?new Xc(d):null;this.m=new dd(this);this.Ma=new dd(this);this.Da=new kd;this.mc=-1}A(wd,P);var xd=(ud||vd)&&!L("533.17.9");g=wd.prototype;g.Od=!0;g.kd=!0;g.Sc=!1;g.Gd=!0;g.Fd=!0;g.mb=null;g.c=null;g.Eb="";g.da=!1;g.Kb=!1;
g.Rc=!0;function yd(a,b){ea(b)&&1==b.nodeType&&bd(b,"haspopup",!0);a.m.F(b,"focus",a.xb);a.m.F(b,"blur",a.wb);if(!a.c&&(a.Ma.F(b,"keydown",a.uc),ea(b)&&1==b.nodeType)){var c;a:{var d=N(b);try{c=d&&d.activeElement;break a}catch(e){}c=null}c==b&&zd(a,b)}}g.pb=function(a){for(var b=0;b<arguments.length;b++)yd(this,arguments[b])};g.e=function(){wd.k.e.call(this);null!=this.mb&&window.clearTimeout(this.mb);this.m.S();delete this.m;this.Ma.S();this.Da.S();Fb(this.d)};
function Ad(a){a.d?a.d.setInterval(300):a.d=new Xc(300)}
function Bd(a,b){switch(b.keyCode){case 40:if(a.h.H.M){a.Sc?qc(a.h):pc(a.h);b.preventDefault();return}if(!a.sa){a.update(!0);b.preventDefault();return}break;case 38:if(a.h.H.M){a.Sc?pc(a.h):qc(a.h);b.preventDefault();return}break;case 9:if(!a.h.H.M||b.shiftKey||a.zd)a.h.I();else if(a.update(),mc(a.h)&&a.Cc){b.preventDefault();return}break;case 13:if(a.h.H.M){if(a.update(),mc(a.h)){b.preventDefault();b.stopPropagation();return}}else a.h.I();break;case 27:if(a.h.H.M){a.h.I();b.preventDefault();b.stopPropagation();
return}break;case 229:if(!a.da){a.da||(a.m.F(a.c,"keyup",a.wc),a.m.F(a.c,"keypress",a.vc),a.da=!0);return}break;default:a.d&&!a.Rc&&(a.d.stop(),a.d.start())}Cd(a,b)}function Cd(a,b){var c=a.sa&&b.charCode&&-1!=a.Ia.indexOf(String.fromCharCode(b.charCode));a.Gd&&c&&a.update();a.Fd&&c&&mc(a.h)&&b.preventDefault()}g.nd=function(){return!1};g.xb=function(a){zd(this,a.target||null)};
function zd(a,b){a.Ma.Fa();a.h&&nc(a.h);b!=a.c&&(a.c=b,a.d&&(a.d.start(),a.m.F(a.d,Yc,a.Bc)),a.Eb=a.c.value,ld(a.Da,a.c),a.m.F(a.Da,"key",a.xc),a.m.F(a.c,"mousedown",a.yc),H&&a.m.F(a.c,"keypress",a.tc))}g.wb=function(){xd?this.mb=window.setTimeout(y(this.Dc,this),0):this.Dc()};
g.Dc=function(){this.c&&(this.m.A(this.Da,"key",this.xc),this.Da.detach(),this.m.A(this.c,"keyup",this.nd),this.m.A(this.c,"mousedown",this.yc),H&&this.m.A(this.c,"keypress",this.tc),this.da&&Dd(this),this.c=null,this.d&&(this.d.stop(),this.m.A(this.d,Yc,this.Bc)),this.h&&oc(this.h))};g.Bc=function(){this.update()};g.uc=function(a){this.xb(a)};g.xc=function(a){this.mc=a.keyCode;this.h&&Bd(this,a)};g.vc=function(){this.da&&229!=this.mc&&Dd(this)};
g.wc=function(a){this.da&&(13==a.keyCode||77==a.keyCode&&a.ctrlKey)&&Dd(this)};g.yc=function(){};function Dd(a){a.da&&(a.da=!1,a.m.A(a.c,"keypress",a.vc),a.m.A(a.c,"keyup",a.wc))}g.tc=function(a){Cd(this,a)};
g.update=function(a){if(this.c&&(a||this.c.value!=this.Eb)){if(a||!this.Kb){a=sc(this.c)[0];var b=this.c.value;a=tc(this,b)[rc(this,b,a)];a=this.Oc?String(a).replace(this.Oc,""):a;if(this.h){this.h.n=this.c;var b=this.h,c=this.c.value;b.L!=a&&(b.L=a,b.aa.cb(b.L,b.vd,y(b.sd,b),c),nc(b))}}this.Eb=this.c.value}this.Kb=!1};function rc(a,b,c){a=tc(a,b);if(c==b.length)return a.length-1;for(var d=b=0,e=0;d<a.length&&e<=c;d++)e+=a[d].length,b=d;return b}
function tc(a,b){if(!a.sa)return[b];for(var c=String(b).split(""),d=[],e=[],f=0,h=!1;f<c.length;f++)a.pc&&-1!=a.pc.indexOf(c[f])?(a.kd&&!h&&(d.push(e.join("")),e.length=0),e.push(c[f]),h=!h):h||-1==a.Ia.indexOf(c[f])?e.push(c[f]):(e.push(c[f]),d.push(e.join("")),e.length=0);d.push(e.join(""));return d};function Ed(a){if("function"==typeof a.P)return a.P();if(u(a))return a.split("");if(da(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Na(a)}function Fd(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(da(a)||u(a))E(a,b,c);else{var d;if("function"==typeof a.Y)d=a.Y();else if("function"!=typeof a.P)if(da(a)||u(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=Oa(a);else d=void 0;for(var e=Ed(a),f=e.length,h=0;h<f;h++)b.call(c,e[h],d&&d[h],a)}};function Gd(a,b){this.R={};this.j=[];this.i=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof Gd?(c=a.Y(),d=a.P()):(c=Oa(a),d=Na(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}}g=Gd.prototype;g.ac=function(){return this.i};g.P=function(){Hd(this);for(var a=[],b=0;b<this.j.length;b++)a.push(this.R[this.j[b]]);return a};g.Y=function(){Hd(this);return this.j.concat()};
g.xa=function(a){return Id(this.R,a)};g.equals=function(a,b){if(this===a)return!0;if(this.i!=a.ac())return!1;var c=b||Jd;Hd(this);for(var d,e=0;d=this.j[e];e++)if(!c(this.get(d),a.get(d)))return!1;return!0};function Jd(a,b){return a===b}g.isEmpty=function(){return 0==this.i};g.clear=function(){this.R={};this.i=this.j.length=0};g.remove=function(a){return Id(this.R,a)?(delete this.R[a],this.i--,this.j.length>2*this.i&&Hd(this),!0):!1};
function Hd(a){if(a.i!=a.j.length){for(var b=0,c=0;b<a.j.length;){var d=a.j[b];Id(a.R,d)&&(a.j[c++]=d);b++}a.j.length=c}if(a.i!=a.j.length){for(var e={},c=b=0;b<a.j.length;)d=a.j[b],Id(e,d)||(a.j[c++]=d,e[d]=1),b++;a.j.length=c}}g.get=function(a,b){return Id(this.R,a)?this.R[a]:b};g.set=function(a,b){Id(this.R,a)||(this.i++,this.j.push(a));this.R[a]=b};g.forEach=function(a,b){for(var c=this.Y(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};g.clone=function(){return new Gd(this)};
function Id(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var Kd=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;function Ld(a){if(Md){Md=!1;var b=n.location;if(b){var c=b.href;if(c&&(c=(c=Ld(c)[3]||null)?decodeURI(c):c)&&c!=b.hostname)throw Md=!0,Error();}}return a.match(Kd)}var Md=K;function Nd(a,b){var c;if(a instanceof Nd)this.D=p(b)?b:a.D,Od(this,a.ca),c=a.ma,U(this),this.ma=c,c=a.T,U(this),this.T=c,Pd(this,a.ta),this.setPath(a.getPath()),Qd(this,a.w.clone()),c=a.fa,U(this),this.fa=c;else if(a&&(c=Ld(String(a)))){this.D=!!b;Od(this,c[1]||"",!0);var d=c[2]||"";U(this);this.ma=Rd(d);d=c[3]||"";U(this);this.T=Rd(d,!0);Pd(this,c[4]);this.setPath(c[5]||"",!0);Qd(this,c[6]||"",!0);c=c[7]||"";U(this);this.fa=Rd(c)}else this.D=!!b,this.w=new Sd(null,0,this.D)}g=Nd.prototype;
g.ca="";g.ma="";g.T="";g.ta=null;g.ab="";g.fa="";g.rd=!1;g.D=!1;g.toString=function(){var a=[],b=this.ca;b&&a.push(Td(b,Ud,!0),":");if(b=this.T){a.push("//");var c=this.ma;c&&a.push(Td(c,Ud,!0),"@");a.push(encodeURIComponent(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.ta;null!=b&&a.push(":",String(b))}if(b=this.getPath())this.T&&"/"!=b.charAt(0)&&a.push("/"),a.push(Td(b,"/"==b.charAt(0)?Vd:Wd,!0));(b=this.w.toString())&&a.push("?",b);(b=this.fa)&&a.push("#",Td(b,Xd));return a.join("")};
g.resolve=function(a){var b=this.clone(),c=!!a.ca;c?Od(b,a.ca):c=!!a.ma;if(c){var d=a.ma;U(b);b.ma=d}else c=!!a.T;c?(d=a.T,U(b),b.T=d):c=null!=a.ta;d=a.getPath();if(c)Pd(b,a.ta);else if(c=!!a.ab){if("/"!=d.charAt(0))if(this.T&&!this.ab)d="/"+d;else{var e=b.getPath().lastIndexOf("/");-1!=e&&(d=b.getPath().substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(C(e,"./")||C(e,"/.")){for(var d=0==e.lastIndexOf("/",0),e=e.split("/"),f=[],h=0;h<e.length;){var k=e[h++];"."==k?d&&h==e.length&&f.push(""):".."==
k?((1<f.length||1==f.length&&""!=f[0])&&f.pop(),d&&h==e.length&&f.push("")):(f.push(k),d=!0)}d=f.join("/")}else d=e}c?b.setPath(d):c=""!==a.w.toString();c?Qd(b,Rd(a.w.toString())):c=!!a.fa;c&&(a=a.fa,U(b),b.fa=a);return b};g.clone=function(){return new Nd(this)};function Od(a,b,c){U(a);a.ca=c?Rd(b,!0):b;a.ca&&(a.ca=a.ca.replace(/:$/,""))}function Pd(a,b){U(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.ta=b}else a.ta=null}g.getPath=function(){return this.ab};
g.setPath=function(a,b){U(this);this.ab=b?Rd(a,!0):a;return this};function Qd(a,b,c){U(a);b instanceof Sd?(a.w=b,a.w.Lb(a.D)):(c||(b=Td(b,Yd)),a.w=new Sd(b,0,a.D))}function Zd(a,b,c){U(a);q(c)||(c=[String(c)]);a.w.setValues(b,c)}function U(a){if(a.rd)throw Error("Tried to modify a read-only Uri");}g.Lb=function(a){this.D=a;this.w&&this.w.Lb(a);return this};function Rd(a,b){return a?b?decodeURI(a):decodeURIComponent(a):""}
function Td(a,b,c){return u(a)?(a=encodeURI(a).replace(b,$d),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function $d(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Ud=/[#\/\?@]/g,Wd=/[\#\?:]/g,Vd=/[\#\?]/g,Yd=/[\#\?@]/g,Xd=/#/g;function Sd(a,b,c){this.t=a||null;this.D=!!c}
function ae(a){if(!a.l&&(a.l=new Gd,a.i=0,a.t))for(var b=a.t.split("\x26"),c=0;c<b.length;c++){var d=b[c].indexOf("\x3d"),e=null,f=null;0<=d?(e=b[c].substring(0,d),f=b[c].substring(d+1)):e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=be(a,e);a.add(e,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}g=Sd.prototype;g.l=null;g.i=null;g.ac=function(){ae(this);return this.i};g.add=function(a,b){ae(this);this.t=null;a=be(this,a);var c=this.l.get(a);c||this.l.set(a,c=[]);c.push(b);this.i++;return this};
g.remove=function(a){ae(this);a=be(this,a);return this.l.xa(a)?(this.t=null,this.i-=this.l.get(a).length,this.l.remove(a)):!1};g.clear=function(){this.l=this.t=null;this.i=0};g.isEmpty=function(){ae(this);return 0==this.i};g.xa=function(a){ae(this);a=be(this,a);return this.l.xa(a)};g.Y=function(){ae(this);for(var a=this.l.P(),b=this.l.Y(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
g.P=function(a){ae(this);var b=[];if(u(a))this.xa(a)&&(b=Ha(b,this.l.get(be(this,a))));else{a=this.l.P();for(var c=0;c<a.length;c++)b=Ha(b,a[c])}return b};g.set=function(a,b){ae(this);this.t=null;a=be(this,a);this.xa(a)&&(this.i-=this.l.get(a).length);this.l.set(a,[b]);this.i++;return this};g.get=function(a,b){var c=a?this.P(a):[];return 0<c.length?String(c[0]):b};g.setValues=function(a,b){this.remove(a);0<b.length&&(this.t=null,this.l.set(be(this,a),Ia(b)),this.i+=b.length)};
g.toString=function(){if(this.t)return this.t;if(!this.l)return"";for(var a=[],b=this.l.Y(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.P(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="\x3d"+encodeURIComponent(String(d[f])));a.push(h)}return this.t=a.join("\x26")};g.clone=function(){var a=new Sd;a.t=this.t;this.l&&(a.l=this.l.clone(),a.i=this.i);return a};function be(a,b){var c=String(b);a.D&&(c=c.toLowerCase());return c}
g.Lb=function(a){a&&!this.D&&(ae(this),this.t=null,this.l.forEach(function(a,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.setValues(d,a))},this));this.D=a};g.extend=function(a){for(var b=0;b<arguments.length;b++)Fd(arguments[b],function(a,b){this.add(b,a)},this)};function ce(a){return eval("("+a+")")};function de(){}de.prototype.Ub=null;function ee(a){var b;(b=a.Ub)||(b={},fe(a)&&(b[0]=!0,b[1]=!0),b=a.Ub=b);return b};var ge;function he(){}A(he,de);function ie(a){return(a=fe(a))?new ActiveXObject(a):new XMLHttpRequest}function fe(a){if(!a.hc&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.hc=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.hc}ge=new he;function je(a){T.call(this);this.headers=new Gd;this.lb=a||null;this.X=!1;this.kb=this.a=null;this.Xa=this.Db="";this.ga=this.yb=this.Ta=this.ub=!1;this.gb=0;this.fb=null;this.Gc=ke;this.Pb=this.Pd=!1}A(je,T);var ke="",le=/^https?$/i,me=["POST","PUT"];g=je.prototype;
g.send=function(a,b,c,d){if(this.a)throw Error("[goog.net.XhrIo] Object is active with another request\x3d"+this.Db+"; newUri\x3d"+a);b=b?b.toUpperCase():"GET";this.Db=a;this.Xa="";this.ub=!1;this.X=!0;this.a=this.lb?ie(this.lb):ie(ge);this.kb=this.lb?ee(this.lb):ee(ge);this.a.onreadystatechange=y(this.zc,this);try{this.yb=!0,this.a.open(b,String(a),!0),this.yb=!1}catch(e){this.Pa(5,e);return}a=c||"";var f=this.headers.clone();d&&Fd(d,function(a,b){f.set(b,a)});d=Ea(f.Y());c=n.FormData&&a instanceof
n.FormData;!(0<=za(me,b))||d||c||f.set("Content-Type","application/x-www-form-urlencoded;charset\x3dutf-8");f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.Gc&&(this.a.responseType=this.Gc);"withCredentials"in this.a&&(this.a.withCredentials=this.Pd);try{ne(this),0<this.gb&&((this.Pb=oe(this.a))?(this.a.timeout=this.gb,this.a.ontimeout=y(this.la,this)):this.fb=Zc(this.la,this.gb,this)),this.Ta=!0,this.a.send(a),this.Ta=!1}catch(h){this.Pa(5,h)}};
function oe(a){return H&&L(9)&&v(a.timeout)&&p(a.ontimeout)}function Ga(a){return"content-type"==a.toLowerCase()}g.la=function(){"undefined"!=typeof aa&&this.a&&(this.Xa="Timed out after "+this.gb+"ms, aborting",this.dispatchEvent("timeout"),this.abort(8))};g.Pa=function(a,b){this.X=!1;this.a&&(this.ga=!0,this.a.abort(),this.ga=!1);this.Xa=b;pe(this);qe(this)};function pe(a){a.ub||(a.ub=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))}
g.abort=function(){this.a&&this.X&&(this.X=!1,this.ga=!0,this.a.abort(),this.ga=!1,this.dispatchEvent("complete"),this.dispatchEvent("abort"),qe(this))};g.e=function(){this.a&&(this.X&&(this.X=!1,this.ga=!0,this.a.abort(),this.ga=!1),qe(this,!0));je.k.e.call(this)};g.zc=function(){this.Aa||(this.yb||this.Ta||this.ga?re(this):this.yd())};g.yd=function(){re(this)};
function re(a){if(a.X&&"undefined"!=typeof aa&&(!a.kb[1]||4!=se(a)||2!=a.getStatus()))if(a.Ta&&4==se(a))Zc(a.zc,0,a);else if(a.dispatchEvent("readystatechange"),4==se(a)){a.X=!1;try{var b=a.getStatus(),c;a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=Ld(String(a.Db))[1]||null;if(!f&&self.location)var h=self.location.protocol,f=h.substr(0,h.length-1);e=!le.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),
a.dispatchEvent("success");else{var k;try{k=2<se(a)?a.a.statusText:""}catch(l){k=""}a.Xa=k+" ["+a.getStatus()+"]";pe(a)}}finally{qe(a)}}}function qe(a,b){if(a.a){ne(a);var c=a.a,d=a.kb[0]?ba:null;a.a=null;a.kb=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}}function ne(a){a.a&&a.Pb&&(a.a.ontimeout=null);v(a.fb)&&(n.clearTimeout(a.fb),a.fb=null)}g.Ua=function(){return!!this.a};function se(a){return a.a?a.a.readyState:0}
g.getStatus=function(){try{return 2<se(this)?this.a.status:-1}catch(a){return-1}};g.getResponseHeader=function(a){return this.a&&4==se(this)?this.a.getResponseHeader(a):void 0};g.getAllResponseHeaders=function(){return this.a&&4==se(this)?this.a.getAllResponseHeaders():""};function te(a,b,c){P.call(this);this.Nb=a;this.Ob=!b;this.a=new je(c)}A(te,P);g=te.prototype;g.wd="GET";g.ya=void 0;g.pd=null;g.Cb=null;g.setContent=function(a){this.ya=a};g.Qd=function(a,b,c){var d;c=c.target;try{d=c.a?c.a.responseText:""}catch(e){d=""}c=[];if(d)try{c=ce(d)}catch(f){}b(a,c)};
g.cb=function(a,b,c){var d,e=this.Ob;d=new Nd(this.Nb);U(d);d.w.set("token",a);b=String(b);U(d);d.w.set("max_matches",b);e=String(Number(e));U(d);d.w.set("use_similar",e);if(d=d.toString())a=y(this.Qd,this,a,c),this.a.Ua()&&this.a.abort(),this.Cb&&ac(this.Cb),this.Cb=Zb(this.a,"success",a),this.a.send(d,this.wd,this.ya,this.pd)};g.e=function(){this.a.S();te.k.e.call(this)};function ue(a){if(a.classList)return a.classList;a=a.className;return u(a)&&a.match(/\S+/g)||[]}function ve(a,b){var c;a.classList?c=a.classList.contains(b):(c=ue(a),c=0<=za(c,b));return c}function we(a,b){a.classList?a.classList.add(b):ve(a,b)||(a.className+=0<a.className.length?" "+b:b)}function xe(a,b){if(a.classList)E(b,function(b){we(a,b)});else{var c={};E(ue(a),function(a){c[a]=!0});E(b,function(a){c[a]=!0});a.className="";for(var d in c)a.className+=0<a.className.length?" "+d:d}}
function ye(a,b){a.classList?a.classList.remove(b):ve(a,b)&&(a.className=Aa(ue(a),function(a){return a!=b}).join(" "))}function ze(a,b){a.classList?E(b,function(b){ye(a,b)}):a.className=Aa(ue(a),function(a){return!(0<=za(b,a))}).join(" ")};function Ae(){T.call(this);this.g=Be;this.endTime=this.startTime=null}A(Ae,T);var Be=0;Ae.prototype.V=function(){this.N("begin")};Ae.prototype.ba=function(){this.N("end")};Ae.prototype.N=function(a){this.dispatchEvent(a)};function Ce(a,b,c){P.call(this);this.Gb=a;this.ha=b||0;this.qa=c;this.ad=y(this.ed,this)}A(Ce,P);g=Ce.prototype;g.u=0;g.e=function(){Ce.k.e.call(this);this.stop();delete this.Gb;delete this.qa};g.start=function(a){this.stop();this.u=Zc(this.ad,p(a)?a:this.ha)};g.stop=function(){this.Ua()&&n.clearTimeout(this.u);this.u=0};g.Ua=function(){return 0!=this.u};g.ed=function(){this.u=0;this.Gb&&this.Gb.call(this.qa)};var Qa={},De=null;function Ee(a){a=fa(a);delete Qa[a];Pa()&&De&&De.stop()}function Fe(){De||(De=new Ce(function(){Ge()},20));var a=De;a.Ua()||a.start()}function Ge(){var a=ka();Ma(Qa,function(b){He(b,a)});Pa()||Fe()};function Ie(a,b,c,d){Ae.call(this);if(!q(a)||!q(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.Ja=a;this.gd=b;this.duration=c;this.Rb=d;this.coords=[];this.G=0}A(Ie,Ae);g=Ie.prototype;
g.play=function(a){if(a||this.g==Be)this.G=0,this.coords=this.Ja;else if(1==this.g)return!1;Ee(this);this.startTime=a=ka();-1==this.g&&(this.startTime-=this.duration*this.G);this.endTime=this.startTime+this.duration;this.G||this.V();this.N("play");-1==this.g&&this.N("resume");this.g=1;var b=fa(this);b in Qa||(Qa[b]=this);Fe();He(this,a);return!0};g.stop=function(a){Ee(this);this.g=Be;a&&(this.G=1);Je(this,this.G);this.N("stop");this.ba()};g.pause=function(){1==this.g&&(Ee(this),this.g=-1,this.N("pause"))};
g.e=function(){this.g==Be||this.stop(!1);this.N("destroy");Ie.k.e.call(this)};function He(a,b){a.G=(b-a.startTime)/(a.endTime-a.startTime);1<=a.G&&(a.G=1);Je(a,a.G);1==a.G?(a.g=Be,Ee(a),a.N("finish"),a.ba()):1==a.g&&a.Hb()}function Je(a,b){x(a.Rb)&&(b=a.Rb(b));a.coords=Array(a.Ja.length);for(var c=0;c<a.Ja.length;c++)a.coords[c]=(a.gd[c]-a.Ja[c])*b+a.Ja[c]}g.Hb=function(){this.N("animate")};g.N=function(a){this.dispatchEvent(new Ke(a,this))};
function Ke(a,b){Q.call(this,a);this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.G=b.G;this.state=b.g}A(Ke,Q);function Le(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d}g=Le.prototype;g.clone=function(){return new Le(this.top,this.right,this.bottom,this.left)};g.contains=function(a){return this&&a?a instanceof Le?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};
g.expand=function(a,b,c,d){ea(a)?(this.top-=a.top,this.right+=a.right,this.bottom+=a.bottom,this.left-=a.left):(this.top-=a,this.right+=b,this.bottom+=c,this.left-=d);return this};g.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};g.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};
g.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};g.translate=function(a,b){a instanceof M?(this.left+=a.x,this.right+=a.x,this.top+=a.y,this.bottom+=a.y):(this.left+=a,this.right+=a,v(b)&&(this.top+=b,this.bottom+=b));return this};g.scale=function(a,b){var c=v(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};function Me(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d}g=Me.prototype;g.clone=function(){return new Me(this.left,this.top,this.width,this.height)};g.intersects=function(a){return this.left<=a.left+a.width&&a.left<=this.left+this.width&&this.top<=a.top+a.height&&a.top<=this.top+this.height};
g.contains=function(a){return a instanceof Me?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};function Ne(a,b){var c=b.x<a.left?a.left-b.x:Math.max(b.x-(a.left+a.width),0),d=b.y<a.top?a.top-b.y:Math.max(b.y-(a.top+a.height),0);return c*c+d*d}g.distance=function(a){return Math.sqrt(Ne(this,a))};
g.getCenter=function(){return new M(this.left+this.width/2,this.top+this.height/2)};g.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};g.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
g.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};g.translate=function(a,b){a instanceof M?(this.left+=a.x,this.top+=a.y):(this.left+=a,v(b)&&(this.top+=b));return this};g.scale=function(a,b){var c=v(b)?b:a;this.left*=a;this.width*=a;this.top*=c;this.height*=c;return this};function V(a,b){var c=N(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b)||"":""}function W(a,b){return V(a,b)||(a.currentStyle?a.currentStyle[b]:null)||a.style&&a.style[b]}
function Oe(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}H&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function Pe(a){if(H&&!(H&&8<=bb))return a.offsetParent;var b=N(a),c=W(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=W(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;return null}
function Qe(a){for(var b=new Le(0,Infinity,Infinity,0),c=fb(a),d=c.s.body,e=c.s.documentElement,f=mb(c.s);a=Pe(a);)if(!(H&&0==a.clientWidth||K&&0==a.clientHeight&&a==d)&&a!=d&&a!=e&&"visible"!=W(a,"overflow")){var h=Re(a),k;k=a;if(J&&!L("1.9")){var l=parseFloat(V(k,"borderLeftWidth"));if(Se(k))var r=k.offsetWidth-k.clientWidth-l-parseFloat(V(k,"borderRightWidth")),l=l+r;k=new M(l,parseFloat(V(k,"borderTopWidth")))}else k=new M(k.clientLeft,k.clientTop);h.x+=k.x;h.y+=k.y;b.top=Math.max(b.top,h.y);
b.right=Math.min(b.right,h.x+a.clientWidth);b.bottom=Math.min(b.bottom,h.y+a.clientHeight);b.left=Math.max(b.left,h.x)}d=f.scrollLeft;f=f.scrollTop;b.left=Math.max(b.left,d);b.top=Math.max(b.top,f);c=(nb(c.s)||window).document;c="CSS1Compat"==c.compatMode?c.documentElement:c.body;c=new eb(c.clientWidth,c.clientHeight);b.right=Math.min(b.right,d+c.width);b.bottom=Math.min(b.bottom,f+c.height);return 0<=b.top&&0<=b.left&&b.bottom>b.top&&b.right>b.left?b:null}
function Re(a){var b,c=N(a),d=W(a,"position"),e=J&&c.getBoxObjectFor&&!a.getBoundingClientRect&&"absolute"==d&&(b=c.getBoxObjectFor(a))&&(0>b.screenX||0>b.screenY),f=new M(0,0),h;b=c?N(c):document;h=!H||H&&9<=bb||wb(fb(b))?b.documentElement:b.body;if(a==h)return f;if(a.getBoundingClientRect)b=Oe(a),a=xb(fb(c)),f.x=b.left+a.x,f.y=b.top+a.y;else if(c.getBoxObjectFor&&!e)b=c.getBoxObjectFor(a),a=c.getBoxObjectFor(h),f.x=b.screenX-a.screenX,f.y=b.screenY-a.screenY;else{b=a;do{f.x+=b.offsetLeft;f.y+=b.offsetTop;
b!=a&&(f.x+=b.clientLeft||0,f.y+=b.clientTop||0);if(K&&"fixed"==W(b,"position")){f.x+=c.body.scrollLeft;f.y+=c.body.scrollTop;break}b=b.offsetParent}while(b&&b!=a);if(Ua||K&&"absolute"==d)f.y-=c.body.offsetTop;for(b=a;(b=Pe(b))&&b!=c.body&&b!=h;)f.x-=b.scrollLeft,Ua&&"TR"==b.tagName||(f.y-=b.scrollTop)}return f}function Te(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a}
function Ue(a){var b=Ve;if("none"!=W(a,"display"))return b(a);var c=a.style,d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=f;c.visibility=e;return a}function Ve(a){var b=a.offsetWidth,c=a.offsetHeight,d=K&&!b&&!c;return p(b)&&!d||!a.getBoundingClientRect?new eb(b,c):(a=Oe(a),new eb(a.right-a.left,a.bottom-a.top))}function Se(a){return"rtl"==W(a,"direction")}var We=J?"MozUserSelect":K?"WebkitUserSelect":null;
function Xe(a){var b=a.getElementsByTagName("*");if(We){var c="none";a.style[We]=c;if(b){a=0;for(var d;d=b[a];a++)d.style[We]=c}}else if(H||Ua)if(c="on",a.setAttribute("unselectable",c),b)for(a=0;d=b[a];a++)d.setAttribute("unselectable",c)}function Ye(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;var e=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return e}
function Ze(a,b){var c=a.currentStyle?a.currentStyle[b]:null;return c?Ye(a,c):0}var $e={thin:2,medium:4,thick:6};function af(a,b){if("none"==(a.currentStyle?a.currentStyle[b+"Style"]:null))return 0;var c=a.currentStyle?a.currentStyle[b+"Width"]:null;return c in $e?$e[c]:Ye(a,c)}
function bf(a){if(H&&!(H&&9<=bb)){var b=af(a,"borderLeft"),c=af(a,"borderRight"),d=af(a,"borderTop");a=af(a,"borderBottom");return new Le(d,c,a,b)}b=V(a,"borderLeftWidth");c=V(a,"borderRightWidth");d=V(a,"borderTopWidth");a=V(a,"borderBottomWidth");return new Le(parseFloat(d),parseFloat(c),parseFloat(a),parseFloat(b))}var cf=/matrix\([0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, ([0-9\.\-]+)p?x?, ([0-9\.\-]+)p?x?\)/;function X(a,b,c,d,e){Ie.call(this,b,c,d,e);this.element=a}A(X,Ie);X.prototype.jb=ba;X.prototype.Hb=function(){this.jb();X.k.Hb.call(this)};X.prototype.ba=function(){this.jb();X.k.ba.call(this)};X.prototype.V=function(){this.jb();X.k.V.call(this)};function Z(a,b,c,d,e){v(b)&&(b=[b]);v(c)&&(c=[c]);X.call(this,a,b,c,d,e);if(1!=b.length||1!=c.length)throw Error("Start and end points must be 1D");this.Ya=df}A(Z,X);var ef=1/1024,df=-1;
Z.prototype.jb=function(){var a=this.coords[0];if(Math.abs(a-this.Ya)>=ef){var b=this.element.style;"opacity"in b?b.opacity=a:"MozOpacity"in b?b.MozOpacity=a:"filter"in b&&(b.filter=""===a?"":"alpha(opacity\x3d"+100*a+")");this.Ya=a}};Z.prototype.V=function(){this.Ya=df;Z.k.V.call(this)};Z.prototype.ba=function(){this.Ya=df;Z.k.ba.call(this)};Z.prototype.show=function(){this.element.style.display=""};function ff(a,b,c){Z.call(this,a,1,0,b,c)}A(ff,Z);ff.prototype.V=function(){this.show();ff.k.V.call(this)};
ff.prototype.ba=function(){this.element.style.display="none";ff.k.ba.call(this)};function gf(a,b,c){Z.call(this,a,0,1,b,c)}A(gf,Z);gf.prototype.V=function(){this.show();gf.k.V.call(this)};function hf(a,b){return(b&4&&Se(a)?b^2:b)&-5};function jf(){}jf.bc=function(){return jf.kc?jf.kc:jf.kc=new jf};jf.prototype.qc=0;function kf(a,b,c,d){T.call(this);this.r=a||document.body;this.O=fb(this.r);this.Cd=!a;this.b=null;this.L="";this.f=[];this.ka=[];this.Mc=this.Sa=-1;this.M=!1;this.className="ac-renderer";this.Jb="ac-row";this.nc="active";this.Sb="ac-active";this.qd="ac-highlighted";this.za=b||null;this.Nd=null!=d?d:!0;this.td=!0;this.Ra=!1;this.Dd=!!c;this.hb=!1;this.Za=0;this.Lc=!1}A(kf,T);g=kf.prototype;g.Ga=function(a,b,c){this.L=b;this.f=a;this.Sa=-1;this.Mc=ka();this.n=c;this.ka=[];lf(this)};
g.I=function(){this.n&&cd(this.n,null);this.M&&(this.M=!1,this.n&&bd(this.n,"haspopup",!1),0<this.Za?(Fb(this.oa),this.oa=new ff(this.b,this.Za),this.oa.play()):this.b.style.display="none")};g.show=function(){this.M||(this.M=!0,this.n&&(ad(this.n,"combobox"),bd(this.n,"autocomplete","list"),bd(this.n,"haspopup",!0)),0<this.Za?(Fb(this.oa),this.oa=new gf(this.b,this.Za),this.oa.play()):this.b.style.display="")};
function mf(a,b){var c=0<=b&&b<a.f.length?a.f[b]:void 0,d=0<=b&&b<a.ka.length?a.ka[b]:void 0;if(a.dispatchEvent({type:"rowhilite",Ud:d,row:c?c.data:null})&&(0<=a.Sa&&ze(a.ka[a.Sa],[a.Sb,a.nc]),a.Sa=b,d)){xe(d,[a.Sb,a.nc]);a.n&&cd(a.n,d);var c=a.b,e=Re(d),f=Re(c),h=bf(c),k=e.x-f.x-h.left,e=e.y-f.y-h.top,f=c.clientHeight-d.offsetHeight,h=c.scrollLeft,l=c.scrollTop,h=h+Math.min(k,Math.max(k-(c.clientWidth-d.offsetWidth),0)),l=l+Math.min(e,Math.max(e-f,0)),d=new M(h,l);c.scrollLeft=d.x;c.scrollTop=d.y}}
g.U=function(a){if(-1==a)mf(this,-1);else for(var b=0;b<this.f.length;b++)if(this.f[b].id==a){mf(this,b);break}};function nf(a){if(!a.b){var b=a.O.Xb("div",{style:"display:none"});a.Lc&&(b.style.overflowY="auto");a.b=b;xe(b,ma(a.className).split(" "));ad(b,"listbox");b.id=":"+(jf.bc().qc++).toString(36);a.O.appendChild(a.r,b);S(b,"click",a.ec,!1,a);S(b,"mousedown",a.fc,!1,a);S(b,"mouseover",a.gc,!1,a)}}
function lf(a){nf(a);a.hb&&(a.b.style.visibility="hidden");a.Uc&&(a.b.style.minWidth=a.Uc.clientWidth+"px");a.ka.length=0;a.O.Ad(a.b);if(!a.za||!a.za.Td){var b=null;E(a.f,function(a){var d=a;a=this.L;var e=this.O.Xb("div",{className:this.Jb,id:":"+(jf.bc().qc++).toString(36)});ad(e,"option");if(this.za&&this.za.Ec)this.za.Ec(d,a,e);else if(d=d.data.toString(),"textContent"in e)e.textContent=d;else if(3==e.nodeType)e.data=d;else if(e.firstChild&&3==e.firstChild.nodeType){for(;e.lastChild!=e.firstChild;)e.removeChild(e.lastChild);
e.firstChild.data=d}else tb(e),e.appendChild(N(e).createTextNode(String(d)));a&&this.Nd&&(this.Tc=!1,of(this,e,a));we(e,this.Jb);this.ka.push(e);a=e;this.hb?this.b.insertBefore(a,b):this.O.appendChild(this.b,a);b=a},a)}0==a.f.length?a.I():(a.show(),pf(a),Xe(a.b))}
function pf(a){if(a.n&&a.Cd){var b=a.Xc||a.n,c,d=a.Dd?3:1;a.hb&&(d^=1);c=d;var e=65;a.Lc&&(a.b.style.height="",e|=32);var d=a.b,f=c^1,h,k;if(h=d.offsetParent){var l="HTML"==h.tagName||"BODY"==h.tagName;l&&"static"==W(h,"position")||(k=Re(h),l||(l=(l=Se(h))&&J?-h.scrollLeft:!l||H&&L("8")||"visible"==W(h,"overflowX")?h.scrollLeft:h.scrollWidth-h.clientWidth-h.scrollLeft,k=db(k,new M(l,h.scrollTop))))}h=k||new M;k=Re(b);l=Ue(b);k=new Me(k.x,k.y,l.width,l.height);if(l=Qe(b)){var r=new Me(l.left,l.top,
l.right-l.left,l.bottom-l.top),l=Math.max(k.left,r.left),t=Math.min(k.left+k.width,r.left+r.width);if(l<=t){var z=Math.max(k.top,r.top),r=Math.min(k.top+k.height,r.top+r.height);z<=r&&(k.left=l,k.top=z,k.width=t-l,k.height=r-z)}}l=fb(b);z=fb(d);if(l.s!=z.s){var t=l.s.body,z=nb(z.s),r=new M(0,0),F;F=(F=N(t))?nb(F):window;var Y=t;do{var I;if(F==z)I=Re(Y);else{I=Y;var R=void 0;if(I.getBoundingClientRect)R=Oe(I),R=new M(R.left,R.top);else var R=xb(fb(I)),w=Re(I),R=new M(w.x-R.x,w.y-R.y);w=void 0;if(J&&
!L(12)){w=void 0;w=w=void 0;b:{w=xa();if(void 0===I.style[w]&&(w=(K?"Webkit":J?"Moz":H?"ms":Ua?"O":null)+ya(w),void 0!==I.style[w])){w=(K?"-webkit":J?"-moz":H?"-ms":Ua?"-o":null)+"-transform";break b}w="transform"}w=(w=W(I,w)||W(I,"transform"))?(I=w.match(cf))?new M(parseFloat(I[1]),parseFloat(I[2])):new M(0,0):new M(0,0);w=new M(R.x+w.x,R.y+w.y)}else w=R;I=w}r.x+=I.x;r.y+=I.y}while(F&&F!=z&&(Y=F.frameElement)&&(F=F.parent));t=db(r,Re(t));!H||H&&9<=bb||wb(l)||(t=db(t,xb(l)));k.left+=t.x;k.top+=t.y}var b=
hf(b,c),b=new M(b&2?k.left+k.width:k.left,b&1?k.top+k.height:k.top),b=db(b,h),m;e&&(m=Qe(d))&&(m.top-=h.y,m.right-=h.x,m.bottom-=h.y,m.left-=h.x);b=b.clone();h=hf(d,f);f=Ue(d);c=f.clone();b=b.clone();c=c.clone();k=0;0!=h&&(h&2&&(b.x-=c.width+0),h&1&&(b.y-=c.height+0));e&&(m?(h=b,k=c,l=0,65==(e&65)&&(h.x<m.left||h.x>=m.right)&&(e&=-2),132==(e&132)&&(h.y<m.top||h.y>=m.bottom)&&(e&=-5),h.x<m.left&&e&1&&(h.x=m.left,l|=1),h.x<m.left&&h.x+k.width>m.right&&e&16&&(k.width=Math.max(k.width-(h.x+k.width-m.right),
0),l|=4),h.x+k.width>m.right&&e&1&&(h.x=Math.max(m.right-k.width,m.left),l|=1),e&2&&(l=l|(h.x<m.left?16:0)|(h.x+k.width>m.right?32:0)),h.y<m.top&&e&4&&(h.y=m.top,l|=2),h.y<=m.top&&h.y+k.height<m.bottom&&e&32&&(k.height=Math.max(k.height-(m.top-h.y),0),h.y=m.top,l|=8),h.y>=m.top&&h.y+k.height>m.bottom&&e&32&&(k.height=Math.max(k.height-(h.y+k.height-m.bottom),0),l|=8),h.y+k.height>m.bottom&&e&4&&(h.y=Math.max(m.bottom-k.height,m.top),l|=2),e&8&&(l=l|(h.y<m.top?64:0)|(h.y+k.height>m.bottom?128:0)),
e=l):e=256,k=e);e=new Me(0,0,0,0);e.left=b.x;e.top=b.y;e.width=c.width;e.height=c.height;k&496||(c=new M(e.left,e.top),b=J&&(Va||Wa)&&L("1.9"),c instanceof M?(m=c.x,c=c.y):(m=c,c=void 0),d.style.left=Te(m,b),d.style.top=Te(c,b),c=new eb(e.width,e.height),f==c||f&&c&&f.width==c.width&&f.height==c.height||(e=c,m=wb(fb(N(d))),!H||L("10")||m&&L("8")?(d=d.style,J?d.MozBoxSizing="border-box":K?d.WebkitBoxSizing="border-box":d.boxSizing="border-box",d.width=Math.max(e.width,0)+"px",d.height=Math.max(e.height,
0)+"px"):(f=d.style,m?(H?(m=Ze(d,"paddingLeft"),b=Ze(d,"paddingRight"),c=Ze(d,"paddingTop"),h=Ze(d,"paddingBottom"),m=new Le(c,b,h,m)):(m=V(d,"paddingLeft"),b=V(d,"paddingRight"),c=V(d,"paddingTop"),h=V(d,"paddingBottom"),m=new Le(parseFloat(c),parseFloat(b),parseFloat(h),parseFloat(m))),d=bf(d),f.pixelWidth=e.width-d.left-m.left-m.right-d.right,f.pixelHeight=e.height-d.top-m.top-m.bottom-d.bottom):(f.pixelWidth=e.width,f.pixelHeight=e.height))));a.hb&&(a.b.style.visibility="visible")}}
g.e=function(){this.b&&($b(this.b,"click",this.ec,!1,this),$b(this.b,"mousedown",this.fc,!1,this),$b(this.b,"mouseover",this.gc,!1,this),this.O.removeNode(this.b),this.b=null,this.M=!1);Fb(this.oa);this.r=null;kf.k.e.call(this)};
function of(a,b,c){if(a.Ra||!a.Tc)if(3==b.nodeType){var d=null;q(c)&&1<c.length&&!a.Ra&&(d=Ja(c,1));c=qf(a,c);if(0!=c.length){var e=b.nodeValue,f=a.td?new RegExp("\\b(?:"+c+")","gi"):new RegExp(c,"gi");c=[];for(var h=0,k=f.exec(e),l=0;k;)l++,c.push(e.substring(h,k.index)),c.push(e.substring(k.index,f.lastIndex)),h=f.lastIndex,k=f.exec(e);c.push(e.substring(h));if(1<c.length){d=a.Ra?l:1;for(e=0;e<d;e++)f=2*e,b.nodeValue=c[f],h=a.O.createElement("b"),h.className=a.qd,a.O.appendChild(h,a.O.createTextNode(c[f+
1])),h=b.parentNode.insertBefore(h,b.nextSibling),b.parentNode.insertBefore(a.O.createTextNode(""),h.nextSibling),b=h.nextSibling;b.nodeValue=Ja(c,2*d).join("");a.Tc=!0}else d&&of(a,b,d)}}else for(b=b.firstChild;b;)d=b.nextSibling,of(a,b,c),b=d}
function qf(a,b){var c="";if(!b)return c;q(b)&&(b=Aa(b,function(a){return!/^[\s\xa0]*$/.test(null==a?"":String(a))}));a.Ra?q(b)?c=Ba(b,va).join("|"):(c=b.replace(/[\s\xa0]+/g," ").replace(/^\s+|\s+$/g,""),c=va(c),c=c.replace(/ /g,"|")):q(b)?c=0<b.length?va(b[0]):"":/^\W/.test(b)||(c=va(b));return c}function rf(a,b){for(;b&&b!=a.b&&!ve(b,a.Jb);)b=b.parentNode;return b?za(a.ka,b):-1}g.ec=function(a){var b=rf(this,a.target);0<=b&&this.dispatchEvent({type:ic,row:this.f[b].id});a.stopPropagation()};
g.fc=function(a){a.stopPropagation();a.preventDefault()};g.gc=function(a){a=rf(this,a.target);0<=a&&!(300>ka()-this.Mc)&&this.dispatchEvent({type:hc,row:this.f[a].id})};function sf(a,b){var c=a.split("."),d=n;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&p(b)?d[e]=b:d=d[e]?d[e]:d[e]={}};function tf(a,b,c){this.tb=hb(a);this.K=O("INPUT",{type:"text"});this.tb.appendChild(this.K);this.ud=q(b)?new yb(b,c):new te(b,c);this.Bd=new kf(this.tb.parentElement,void 0,!0);this.Q=new wd(null,null,!1);gc.call(this,this.ud,this.Bd,this.Q);this.Q.h=this;this.Q.pb(this.K);this.Q.Cc=!0;this.na=[];S(this,"update",function(a){uf(this,a.row.toString());this.Q.c.value=""},!1,this);S(this.tb,"click",function(){this.K.focus()},!1,this);S(this.K,["change","keydown"],function(){this.K.size=this.K.value.length+
1},!1,this);S(this.K,"keydown",function(a){0==this.K.value.length&&8==a.keyCode&&vf(this);13!=a.keyCode||this.H.M||(a.stopPropagation(),a.preventDefault())},!1,this)}A(tf,gc);tf.prototype.I=function(){tf.k.I.call(this);this.K.value=""};tf.prototype.Ga=function(a,b){var c=Aa(a,function(a){var b=a.toString();return Da(this.na,function(a){return a.Qb!=b})},this);tf.k.Ga.call(this,c,b)};
function uf(a,b){var c=O("A",{href:"#","class":"mc-tag-remove"},"X"),d=O("DIV","mc-tag",b,c),e=a.na.push({Qb:b,fd:d,cd:c});S(c,"click",function(a){vf(this,e-1);this.K.focus();a.preventDefault()},!1,a);ub(d,a.K)}function vf(a,b){u(b)&&(b=Fa(a.na,function(a){return a.Qb==b}));var c=null!=b?a.na[b]:a.na.pop();null!=c&&(bc(c.cd),vb(c.fd),null!=b&&delete a.na[b])}tf.prototype.P=function(){return Ba(this.na,function(a){return a.Qb})};sf("kt.MultiComplete",tf);/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
function wf(a,b){this.eb=[];this.rc=a;this.Yb=b||null;this.Ca=this.pa=!1;this.W=void 0;this.Mb=this.Zc=this.qb=!1;this.ib=0;this.r=null;this.sb=0}wf.prototype.cancel=function(a){if(this.pa)this.W instanceof wf&&this.W.cancel();else{if(this.r){var b=this.r;delete this.r;a?b.cancel(a):(b.sb--,0>=b.sb&&b.cancel())}this.rc?this.rc.call(this.Yb,this):this.Mb=!0;this.pa||(a=new xf,yf(this),zf(this,!1,a))}};wf.prototype.Wb=function(a,b){this.qb=!1;zf(this,a,b)};
function zf(a,b,c){a.pa=!0;a.W=c;a.Ca=!b;Af(a)}function yf(a){if(a.pa){if(!a.Mb)throw new Bf;a.Mb=!1}}function Cf(a,b,c,d){a.eb.push([b,c,d]);a.pa&&Af(a)}wf.prototype.then=function(a,b,c){var d,e,f=new Jc(function(a,b){d=a;e=b});Cf(this,d,function(a){a instanceof xf?f.cancel():e(a)});return f.then(a,b,c)};xc(wf);function Df(a){return Ca(a.eb,function(a){return x(a[1])})}
function Af(a){if(a.ib&&a.pa&&Df(a)){var b=a.ib,c=Ef[b];c&&(n.clearTimeout(c.u),delete Ef[b]);a.ib=0}a.r&&(a.r.sb--,delete a.r);for(var b=a.W,d=c=!1;a.eb.length&&!a.qb;){var e=a.eb.shift(),f=e[0],h=e[1],e=e[2];if(f=a.Ca?h:f)try{var k=f.call(e||a.Yb,b);p(k)&&(a.Ca=a.Ca&&(k==b||k instanceof Error),a.W=b=k);yc(b)&&(d=!0,a.qb=!0)}catch(l){b=l,a.Ca=!0,Df(a)||(c=!0)}}a.W=b;d&&(k=y(a.Wb,a,!0),d=y(a.Wb,a,!1),b instanceof wf?(Cf(b,k,d),b.Zc=!0):b.then(k,d));c&&(b=new Ff(b),Ef[b.u]=b,a.ib=b.u)}
function Bf(){B.call(this)}A(Bf,B);Bf.prototype.message="Deferred has already fired";Bf.prototype.name="AlreadyCalledError";function xf(){B.call(this)}A(xf,B);xf.prototype.message="Deferred was canceled";xf.prototype.name="CanceledError";function Ff(a){this.u=n.setTimeout(y(this.Kd,this),0);this.Pa=a}Ff.prototype.Kd=function(){delete Ef[this.u];throw this.Pa;};var Ef={};function Gf(a,b){var c=b||{},d=c.document||document,e=document.createElement("SCRIPT"),f={Kc:e,la:void 0},h=new wf(Hf,f),k=null,l=null!=c.timeout?c.timeout:5E3;0<l&&(k=window.setTimeout(function(){If(e,!0);var b=new Jf(Kf,"Timeout reached for loading script "+a);yf(h);zf(h,!1,b)},l),f.la=k);e.onload=e.onreadystatechange=function(){e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(If(e,c.bd||!1,k),yf(h),zf(h,!0,null))};e.onerror=function(){If(e,!0,k);var b=new Jf(Lf,"Error while loading script "+
a);yf(h);zf(h,!1,b)};kb(e,{type:"text/javascript",charset:"UTF-8",src:a});Mf(d).appendChild(e);return h}function Mf(a){var b=a.getElementsByTagName("HEAD");return b&&0!=b.length?b[0]:a.documentElement}function Hf(){if(this&&this.Kc){var a=this.Kc;a&&"SCRIPT"==a.tagName&&If(a,!0,this.la)}}function If(a,b,c){null!=c&&n.clearTimeout(c);a.onload=ba;a.onerror=ba;a.onreadystatechange=ba;b&&window.setTimeout(function(){vb(a)},0)}var Lf=0,Kf=1;
function Jf(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);B.call(this,c);this.code=a}A(Jf,B);function Nf(a,b){this.Md=new Nd(a);this.$c=b?b:"callback";this.la=5E3}var Of=0;Nf.prototype.send=function(a,b,c,d){a=a||null;d=d||"_"+(Of++).toString(36)+ka().toString(36);n._callbacks_||(n._callbacks_={});var e=this.Md.clone();if(a)for(var f in a)a.hasOwnProperty&&!a.hasOwnProperty(f)||Zd(e,f,a[f]);b&&(n._callbacks_[d]=Pf(d,b),Zd(e,this.$c,"_callbacks_."+d));b=Gf(e.toString(),{timeout:this.la,bd:!0});Cf(b,null,Qf(d,a,c),void 0);return{u:d,Zb:b}};
Nf.prototype.cancel=function(a){a&&(a.Zb&&a.Zb.cancel(),a.u&&Rf(a.u,!1))};function Qf(a,b,c){return function(){Rf(a,!1);c&&c(b)}}function Pf(a,b){return function(c){Rf(a,!0);b.apply(void 0,arguments)}}function Rf(a,b){n._callbacks_[a]&&(b?delete n._callbacks_[a]:n._callbacks_[a]=ba)};function Sf(a,b){this.Nb=a||"http://open.mapquestapi.com/nominatim/v1/search";this.Ea=b||{};this.lc=new Nf(this.Nb,"json_callback")}
Sf.prototype.cb=function(a,b,c){this.Ea.q=a;this.Ea.format="json";this.Ea.addressdetails=1;this.Ea.limit=b;a&&1!=a.length?(1==b&&(this.xd=a),1<b&&a===this.xd||(null!==this.Fc&&this.lc.cancel(this.Fc),this.Fc=this.lc.send(this.Ea,function(b){function e(a){var b=[];E(a,function(a){var c=a.boundingbox;b.push({formatted_address:a.display_name,type:a.type,bounds:c?[parseFloat(c[2]),parseFloat(c[0]),parseFloat(c[3]),parseFloat(c[1])]:null,viewport:null})},this);return b}var f=Aa(b,function(a){return("place"==
a["class"]||"highway"==a["class"]||"boundary"==a["class"])&&"state"!==a.type&&"country"!==a.type}),h=Aa(b,function(a){return"place"!==a["class"]&&"highway"!==a["class"]});0<f.length?(E(f,function(a){var b="us"==a.address.country_code?a.address.state:"gb"==a.address.country_code?"UK":"de"==a.address.country_code?"Germany":a.address.country,c=a.address.city?a.address.city:a.address.town?a.address.town:a.address.village?a.address.village:a.address.hamlet;if("suburb"==a.type)var d=a.address.suburb+(c?
", "+c:"")+", "+b;d="city"==a.type||"town"==a.type||"village"==a.type||"hamlet"==a.type?c+", "+b:"way"==a.osm_type?(a.address.road?a.address.road:a.address.pedestrian)+", "+c+", "+b:"house"==a.type?a.address.road+" "+a.address.house_number+", "+c+", "+b:a.display_name;a.display_name=d}),c(a,e(Ha(f,h)))):c(a,e(b))}))):c(a,[])};function Tf(a,b,c){this.zb=a;var d=new kf(null,{Ec:function(a,b,c){c.innerHTML=a.data.formatted_address+" ("+a.data.type+")"}});d.Uc=this.zb;this.aa=new Sf(b,c);this.ra=new wd(null,null,!1);Ad(this.ra);this.ra.Rc=!1;this.ra.h=this;gc.call(this,this.aa,d,this.ra);this.$b=!1;this.F("update",function(b){a.value=b.row?b.row.formatted_address:""});this.enable(!0)}A(Tf,gc);
Tf.prototype.enable=function(a){if(this.$b!=a)if(this.$b=a)yd(this.ra,this.zb);else{a=this.ra;var b=this.zb;b==a.c&&a.wb();a.m.A(b,"focus",a.xb);a.m.A(b,"blur",a.wb);a.c||a.Ma.A(b,"keydown",a.uc)}};Tf.prototype.search=function(a,b,c){this.aa.cb(a,b,c)};sf("kt.Nominatim",Tf);function Uf(a,b,c,d){this.ya=O("DIV","popup-content");this.La=null;c=c?O("A","popup-close","X"):null;this.b=O("DIV","popup");a&&rb(this.b,O("DIV","popup-title",a));c&&this.b.appendChild(c);this.b.appendChild(this.ya);this.Ic=b?O("DIV","popup-bg",this.b):this.b;c&&S(c,"click",function(a){this.setVisible(!1);d&&d();a.preventDefault()},!1,this)}Uf.prototype.setVisible=function(a){a?document.body.appendChild(this.Ic):vb(this.Ic)};Uf.prototype.append=function(a){sb(this.ya,arguments)};
Uf.prototype.ob=function(a){this.La||(this.La=O("DIV","popup-actions"),this.b.appendChild(this.La));sb(this.La,arguments)};sf("kt.Popup",Uf);sf("kt.alert",function(a,b,c){var d=new Uf(b,!0);d.append(String(a));a=O("DIV","btn",c||"OK");d.ob(a);S(a,"click",function(a){d.setVisible(!1);a.preventDefault()});d.setVisible(!0)});
sf("kt.prompt",function(a,b,c,d,e,f){var h=new Uf(c,!0),k=O("INPUT",{type:"text",value:f||""});h.append(String(a),k);a=O("DIV","btn-light",d||"OK");e=O("DIV","btn-dark",e||"Cancel");h.ob(e,a);S(a,"click",function(a){h.setVisible(!1);b(k.value);a.preventDefault()});S(e,"click",function(a){h.setVisible(!1);b(null);a.preventDefault()});h.setVisible(!0)});
sf("kt.confirm",function(a,b,c,d,e){var f=new Uf(c,!0,!0,function(){b(null)});f.append(String(a));a=O("DIV","btn-light",d||"Yes");e=O("DIV","btn-dark",e||"No");f.ob(a,e);S(a,"click",function(a){f.setVisible(!1);b(!0);a.preventDefault()});S(e,"click",function(a){f.setVisible(!1);b(!1);a.preventDefault()});f.setVisible(!0)});sf("kt.decorate",function(){E(ib(),function(a){new Tf(a)})});
